name: DEV Package and TestPyPi Upload

on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - develop
    paths-ignore:
      - ".github/"
      - "tests/"
      - ".pre-commit-config.yaml"
      - "**/*.rst"
      - "**/*.md"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/develop' && startsWith(github.event.head_commit.message, 'v'))
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TEST_TOKEN }}
          python_version: ${{ env.PYTHON_BUILD_VERSION }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
